# Generated by Django 5.2.9 on 2025-12-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_analysisjob_status_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('extracting', 'Extracting Questions'), ('classifying', 'Classifying'), ('analyzing', 'Analyzing'), ('embedding', 'Generating Embeddings'), ('detecting', 'Detecting Duplicates'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20),
        ),
    ]
