# Generated by Django 5.2.10 on 2026-01-08 09:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0004_alter_analysisjob_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempPaper",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="jobs/%Y/%m/%d/")),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("year", models.CharField(blank=True, max_length=50)),
                ("exam_name", models.CharField(blank=True, max_length=255)),
                (
                    "pdf_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("text", "Text-based PDF"),
                            ("scanned", "Scanned/Image PDF"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "raw_text",
                    models.TextField(
                        blank=True, help_text="Raw extracted text (UNCHANGED)"
                    ),
                ),
                ("page_count", models.PositiveIntegerField(default=0)),
                ("extracted", models.BooleanField(default=False)),
                ("extraction_error", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Temporary Paper",
                "verbose_name_plural": "Temporary Papers",
                "ordering": ["year", "uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="TempQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_number", models.CharField(max_length=20)),
                (
                    "part",
                    models.CharField(
                        choices=[("A", "Part A (3 marks)"), ("B", "Part B (14 marks)")],
                        max_length=1,
                    ),
                ),
                ("marks", models.PositiveIntegerField(default=3)),
                (
                    "raw_text",
                    models.TextField(
                        help_text="Original question text with all formatting"
                    ),
                ),
                (
                    "normalized_text",
                    models.TextField(
                        blank=True,
                        help_text="Cleaned text for semantic analysis (no numbers, marks, years)",
                    ),
                ),
                (
                    "module_number",
                    models.PositiveIntegerField(
                        help_text="Module 1-5 based on KTU rules", null=True
                    ),
                ),
                ("has_sub_parts", models.BooleanField(default=False)),
                ("sub_parts", models.JSONField(blank=True, default=list)),
                ("is_or_question", models.BooleanField(default=False)),
                ("has_images", models.BooleanField(default=False)),
                (
                    "images",
                    models.JSONField(
                        blank=True, default=list, help_text="Extracted image data"
                    ),
                ),
                (
                    "embedding",
                    models.JSONField(
                        blank=True,
                        help_text="384-dim vector from sentence-transformer",
                        null=True,
                    ),
                ),
                (
                    "cluster_id",
                    models.IntegerField(
                        help_text="HDBSCAN cluster ID (-1 = noise)", null=True
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["paper__year", "question_number"],
            },
        ),
        migrations.CreateModel(
            name="TempTopicCluster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("module_number", models.PositiveIntegerField()),
                ("cluster_id", models.IntegerField(help_text="HDBSCAN cluster ID")),
                (
                    "topic_label",
                    models.CharField(
                        help_text="Human-readable topic name (from cluster centroid)",
                        max_length=500,
                    ),
                ),
                (
                    "representative_question",
                    models.TextField(
                        blank=True, help_text="Most common question variant"
                    ),
                ),
                (
                    "frequency",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of DISTINCT YEARS this topic appeared",
                    ),
                ),
                (
                    "years_appeared",
                    models.JSONField(
                        default=list, help_text='List of years: ["2021", "2022", ...]'
                    ),
                ),
                ("total_marks", models.PositiveIntegerField(default=0)),
                ("average_marks", models.FloatField(default=0.0)),
                (
                    "part_a_count",
                    models.PositiveIntegerField(
                        default=0, help_text="How many times appeared in Part A"
                    ),
                ),
                (
                    "part_b_count",
                    models.PositiveIntegerField(
                        default=0, help_text="How many times appeared in Part B"
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0, help_text="(years_appeared / total_years) × 100"
                    ),
                ),
                (
                    "priority_score",
                    models.FloatField(
                        default=0.0, help_text="(2 × frequency) + average_marks"
                    ),
                ),
                (
                    "priority_tier",
                    models.IntegerField(
                        choices=[
                            (1, "Very High Priority"),
                            (2, "High Priority"),
                            (3, "Medium Priority"),
                            (4, "Low Priority"),
                        ],
                        default=4,
                    ),
                ),
                ("question_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["module_number", "priority_tier", "-priority_score"],
            },
        ),
        migrations.RemoveField(
            model_name="analysisjob",
            name="duplicates_found",
        ),
        migrations.RemoveField(
            model_name="analysisjob",
            name="paper",
        ),
        migrations.RemoveField(
            model_name="analysisjob",
            name="questions_classified",
        ),
        migrations.RemoveField(
            model_name="analysisjob",
            name="status_detail",
        ),
        migrations.RemoveField(
            model_name="analysisjob",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="analysisjob",
            name="current_phase",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="analysisjob",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysisjob",
            name="output_pdfs",
            field=models.JSONField(
                default=dict,
                help_text='Module-wise PDF paths: {"module_1": "/path/", ...}',
            ),
        ),
        migrations.AddField(
            model_name="analysisjob",
            name="pdf_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="analysisjob",
            name="subject_name",
            field=models.CharField(
                default="Unknown Subject",
                help_text="Subject name from user input",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="analysisjob",
            name="topics_clustered",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="analysisjob",
            name="total_years",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of distinct years uploaded"
            ),
        ),
        migrations.AddField(
            model_name="analysisjob",
            name="years_list",
            field=models.JSONField(
                default=list, help_text="List of years for confidence calculation"
            ),
        ),
        migrations.AlterField(
            model_name="analysisjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("uploading", "Uploading Files"),
                    ("detecting_pdf_type", "Detecting PDF Type"),
                    ("extracting", "Extracting Questions"),
                    ("mapping_modules", "Mapping to Modules"),
                    ("normalizing", "Normalizing Questions"),
                    ("embedding", "Generating Embeddings"),
                    ("clustering", "Clustering Topics"),
                    ("scoring", "Computing Priority Scores"),
                    ("generating_pdfs", "Generating Module PDFs"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                ],
                default="created",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="analysisjob",
            index=models.Index(
                fields=["status", "-created_at"], name="analysis_an_status_f4a6d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysisjob",
            index=models.Index(
                fields=["expires_at"], name="analysis_an_expires_403e3a_idx"
            ),
        ),
        migrations.AddField(
            model_name="temppaper",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="papers",
                to="analysis.analysisjob",
            ),
        ),
        migrations.AddField(
            model_name="tempquestion",
            name="paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="analysis.temppaper",
            ),
        ),
        migrations.AddField(
            model_name="temptopiccluster",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic_clusters",
                to="analysis.analysisjob",
            ),
        ),
        migrations.AddField(
            model_name="tempquestion",
            name="topic_cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="analysis.temptopiccluster",
            ),
        ),
        migrations.AddIndex(
            model_name="temptopiccluster",
            index=models.Index(
                fields=["module_number", "priority_tier"],
                name="analysis_te_module__09e11c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="temptopiccluster",
            index=models.Index(
                fields=["-priority_score"], name="analysis_te_priorit_5ea9f6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="temptopiccluster",
            unique_together={("job", "module_number", "cluster_id")},
        ),
        migrations.AddIndex(
            model_name="tempquestion",
            index=models.Index(
                fields=["module_number", "part"], name="analysis_te_module__ef908f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tempquestion",
            index=models.Index(
                fields=["cluster_id"], name="analysis_te_cluster_702053_idx"
            ),
        ),
    ]
