# Generated by Django 6.0.1 on 2026-01-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_add_ai_analysis_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cleaned_text',
            field=models.TextField(blank=True, help_text='LLM-cleaned text (if OCR cleaning was used)'),
        ),
        migrations.AddField(
            model_name='question',
            name='ocr_cleaned_by',
            field=models.CharField(blank=True, choices=[('none', 'Not Cleaned'), ('gemini', 'Gemini 1.5 Flash'), ('ollama', 'Ollama')], default='none', help_text='Which LLM was used for OCR cleaning', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='raw_ocr_text',
            field=models.TextField(blank=True, help_text='Original OCR output before LLM cleaning'),
        ),
        migrations.AddField(
            model_name='question',
            name='similarity_method',
            field=models.CharField(blank=True, choices=[('embedding', 'Embedding Only'), ('llm', 'LLM Only'), ('hybrid', 'Hybrid (Embedding + LLM)')], help_text='Method used for similarity detection', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='similarity_reason',
            field=models.TextField(blank=True, help_text='LLM explanation for similarity decision (for edge cases)'),
        ),
    ]
