# Generated by Django 5.2.11 on 2026-02-20 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_production_models"),
        ("papers", "0004_production_models"),
        ("questions", "0005_add_hybrid_llm_fields"),
        ("subjects", "0004_add_university_type_and_public_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionEmbeddingCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vector",
                    models.JSONField(
                        help_text="Sentence-transformer embedding vector stored as a list of floats."
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="all-MiniLM-L6-v2",
                        help_text="Name of the model used to generate this embedding.",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Question Embedding Cache",
                "verbose_name_plural": "Question Embedding Caches",
            },
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["paper", "module"], name="questions_q_paper_i_2b82a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["is_duplicate"], name="questions_q_is_dupl_c730ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["difficulty", "bloom_level"],
                name="questions_q_difficu_7e7299_idx",
            ),
        ),
        migrations.AddField(
            model_name="questionembeddingcache",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embedding_cache",
                to="questions.question",
            ),
        ),
        migrations.AddIndex(
            model_name="questionembeddingcache",
            index=models.Index(
                fields=["question"], name="questions_q_questio_47c8e3_idx"
            ),
        ),
    ]
