# Generated by Django 5.2.11 on 2026-02-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0003_paper_progress_percent_paper_questions_classified_and_more"),
        ("subjects", "0004_add_university_type_and_public_access"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["subject", "status"], name="papers_pape_subject_0eebf1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["file_hash"], name="papers_pape_file_ha_1b7c05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["-created_at"], name="papers_pape_created_660526_idx"
            ),
        ),
    ]
