# Generated by Django 5.2.9 on 2025-12-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_topiccluster_question_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiccluster',
            name='cluster_id',
            field=models.CharField(blank=True, help_text='Cluster ID from algorithm', max_length=100),
        ),
        migrations.AlterField(
            model_name='topiccluster',
            name='priority_tier',
            field=models.IntegerField(default=4, help_text='1=Top, 2=High, 3=Medium, 4=Low'),
        ),
    ]
