# Generated by Django 5.2.10 on 2026-01-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_add_confidence_score_to_topic_cluster"),
        ("analytics", "0003_topiccluster_cluster_id_and_more"),
    ]

    operations = []
