# Generated by Django 5.2.11 on 2026-02-20 08:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_topiccluster_cluster_id_and_more"),
        ("questions", "0005_add_hybrid_llm_fields"),
        ("subjects", "0004_add_university_type_and_public_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topiccluster",
            name="priority_tier",
            field=models.IntegerField(
                choices=[
                    (1, "Top Priority (4+ exams)"),
                    (2, "High Priority (3 exams)"),
                    (3, "Medium Priority (2 exams)"),
                    (4, "Low Priority (1 exam)"),
                ],
                default=4,
                help_text="1=Top, 2=High, 3=Medium, 4=Low",
            ),
        ),
        migrations.CreateModel(
            name="ClusterGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cluster_label", models.IntegerField(db_index=True)),
                ("representative_text", models.TextField(blank=True)),
                (
                    "frequency",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of distinct exam years this topic appeared.",
                    ),
                ),
                ("years_appeared", models.JSONField(blank=True, default=list)),
                ("question_count", models.PositiveIntegerField(default=0)),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cluster_groups",
                        to="subjects.module",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster_groups",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cluster Group",
                "verbose_name_plural": "Cluster Groups",
                "ordering": ["-frequency", "cluster_label"],
            },
        ),
        migrations.CreateModel(
            name="ClusterMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="analytics.clustergroup",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster_memberships",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cluster Membership",
                "verbose_name_plural": "Cluster Memberships",
            },
        ),
        migrations.CreateModel(
            name="PriorityAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tier",
                    models.IntegerField(
                        choices=[
                            (1, "Top Priority (4+ years)"),
                            (2, "High Priority (3 years)"),
                            (3, "Medium Priority (2 years)"),
                            (4, "Low Priority (1 year)"),
                        ],
                        db_index=True,
                        default=4,
                    ),
                ),
                ("tier_label", models.CharField(blank=True, max_length=50)),
                ("frequency", models.PositiveIntegerField(default=0)),
                (
                    "cluster",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="priority_assignment",
                        to="analytics.clustergroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Priority Assignment",
                "verbose_name_plural": "Priority Assignments",
                "ordering": ["tier", "-frequency"],
            },
        ),
        migrations.AddIndex(
            model_name="clustergroup",
            index=models.Index(
                fields=["subject", "module"], name="analytics_c_subject_d778db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clustergroup",
            index=models.Index(
                fields=["-frequency"], name="analytics_c_frequen_d8dc6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clustermembership",
            index=models.Index(
                fields=["cluster", "question"], name="analytics_c_cluster_a7bf8e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clustermembership",
            unique_together={("cluster", "question")},
        ),
        migrations.AddIndex(
            model_name="priorityassignment",
            index=models.Index(fields=["tier"], name="analytics_p_tier_2168c6_idx"),
        ),
    ]
