# Generated by Django 5.2.10 on 2026-01-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_merge_20260108_0916"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topiccluster",
            name="priority_tier",
            field=models.IntegerField(
                choices=[
                    (1, "Top Priority (4+ exams)"),
                    (2, "High Priority (3 exams)"),
                    (3, "Medium Priority (2 exams)"),
                    (4, "Low Priority (1 exam)"),
                ],
                default=4,
                help_text="1=Top, 2=High, 3=Medium, 4=Low",
            ),
        ),
    ]
