# Generated by Django 5.2.11 on 2026-02-20 08:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "0004_add_university_type_and_public_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("module", "Module Report"),
                            ("subject", "Full Subject Report"),
                        ],
                        default="module",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Generated PDF file.",
                        null=True,
                        upload_to="reports/",
                    ),
                ),
                ("file_size_bytes", models.PositiveIntegerField(default=0)),
                ("page_count", models.PositiveIntegerField(default=0)),
                (
                    "generation_meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of settings used during generation.",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for full-subject reports.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to="subjects.module",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Report",
                "verbose_name_plural": "Generated Reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["subject", "module"],
                        name="reports_gen_subject_fbe85c_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="reports_gen_created_8b06be_idx"
                    ),
                ],
            },
        ),
    ]
